#!/usr/bin/env python3
"""Create a structured YouTube Shorts production project.

This utility uses only Python's standard library.
"""

from __future__ import annotations

import argparse
import json
import re
from datetime import datetime
from pathlib import Path


DEFAULT_SCENE_DURATION = 5


def slugify(text: str) -> str:
    """Convert a title into a safe folder/file name."""
    text = text.strip().lower()
    text = re.sub(r"[^a-z0-9\s-]", "", text)
    text = re.sub(r"[\s-]+", "-", text)
    return text.strip("-")


def create_scene_template(scene_number: int) -> dict:
    """Return the default structure for one Shorts scene."""
    return {
        "scene": scene_number,
        "duration_seconds": DEFAULT_SCENE_DURATION,
        "voice_over": "",
        "visual_prompt": "",
        "on_screen_headline": "",
        "on_screen_subheadline": "",
        "status": "draft",
    }


def build_project(title: str, output_dir: Path, scene_count: int) -> Path:
    """Create all files and directories for a new Shorts project."""
    slug = slugify(title)

    if not slug:
        raise ValueError("Project title must contain at least one letter or number.")

    project_dir = output_dir / slug
    scenes_dir = project_dir / "scenes"
    assets_dir = project_dir / "assets"
    export_dir = project_dir / "export"

    for directory in (scenes_dir, assets_dir, export_dir):
        directory.mkdir(parents=True, exist_ok=True)

    scenes = [
        create_scene_template(index)
        for index in range(1, scene_count + 1)
    ]

    project_data = {
        "project": title,
        "created_at": datetime.now().astimezone().isoformat(timespec="seconds"),
        "platform": "YouTube Shorts",
        "target_audience": "USA + Global",
        "aspect_ratio": "9:16",
        "scene_duration_max_seconds": DEFAULT_SCENE_DURATION,
        "scenes": scenes,
        "seo": {
            "title": "",
            "description": "",
            "hashtags": [],
            "tags": [],
        },
        "publishing": {
            "thumbnail_ready": False,
            "voice_over_ready": False,
            "visuals_ready": False,
            "captions_ready": False,
            "metadata_ready": False,
            "final_review": False,
        },
    }

    write_text(
        project_dir / "project.json",
        json.dumps(project_data, indent=2, ensure_ascii=False) + "\n",
    )

    script_lines = [
        f"# {title}",
        "",
        "## Hook",
        "",
        "[Write a strong opening hook here]",
        "",
        "## Voice Over",
        "",
    ]

    for index in range(1, scene_count + 1):
        script_lines.extend(
            [
                f"### Scene {index}",
                f"Duration: {DEFAULT_SCENE_DURATION} seconds",
                "",
                "[Voice-over]",
                "",
                "[Visual direction]",
                "",
                "[Headline]",
                "",
                "[Subheadline]",
                "",
            ]
        )

    script_lines.extend(
        [
            "## CTA",
            "",
            "[Comment question / Follow CTA]",
            "",
            "## SEO",
            "",
            "Title:",
            "",
            "Description:",
            "",
            "Hashtags:",
            "",
            "Tags:",
            "",
        ]
    )

    write_text(project_dir / "SCRIPT.md", "\n".join(script_lines).rstrip() + "\n")

    checklist = """# Publishing Checklist

- [ ] Hook is clear within the first few seconds
- [ ] Voice-over is easy to understand
- [ ] Each scene stays within the planned duration
- [ ] Visuals match the voice-over
- [ ] Facts have been verified
- [ ] On-screen text is readable
- [ ] CTA is included
- [ ] Title is optimized
- [ ] Description is complete
- [ ] Hashtags are relevant
- [ ] Tags are relevant
- [ ] Final video is 9:16
- [ ] Final review completed
"""

    write_text(project_dir / "CHECKLIST.md", checklist)

    readme = f"""# {title}

YouTube Shorts project generated by the YouTube Shorts Content Kit.

## Project

- Target: USA + Global
- Format: 9:16
- Scenes: {scene_count}
- Maximum planned scene duration: {DEFAULT_SCENE_DURATION} seconds

## Files

- project.json - structured project data
- SCRIPT.md - script and scene planning
- CHECKLIST.md - publishing checklist
- scenes/ - scene-specific assets
- assets/ - images, audio, and other source files
- export/ - final output
"""

    write_text(project_dir / "README.md", readme)


def write_text(path: Path, content: str) -> None:
    """Write UTF-8 text consistently."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Create a structured YouTube Shorts project."
    )

    parser.add_argument(
        "title",
        help="Shorts project title",
    )

    parser.add_argument(
        "--scenes",
        type=int,
        default=8,
        help="Number of scenes (default: 8)",
    )

    parser.add_argument(
        "--output",
        type=Path,
        default=Path("projects"),
        help="Output directory (default: projects)",
    )

    args = parser.parse_args()

    if args.scenes < 1:
        raise SystemExit("Scene count must be at least 1.")

    try:
        project_path = build_project(
            title=args.title,
            output_dir=args.output,
            scene_count=args.scenes,
        )
    except ValueError as exc:
        raise SystemExit(str(exc)) from exc

    print()
    print("Project created successfully!")
    print(f"Location: {project_path.resolve()}")
    print()
    print("Generated:")
    print("  - project.json")
    print("  - SCRIPT.md")
    print("  - CHECKLIST.md")
    print("  - README.md")
    print("  - scenes/")
    print("  - assets/")
    print("  - export/")


if __name__ == "__main__":
    main()
